* Serving Flask app "FlaskPlay" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "FlaskPlay.py", line 40, in <module>
    app.run(debug=True)
  File "/root/PycharmProjects/Flasksite/venv/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/root/PycharmProjects/Flasksite/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
OSError: [Errno 98] Address already in use
 * Serving Flask app "FlaskPlay" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "FlaskPlay.py", line 40, in <module>
    app.run(debug=True)
  File "/root/PycharmProjects/Flasksite/venv/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/root/PycharmProjects/Flasksite/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
OSError: [Errno 98] Address already in use
 * Serving Flask app "FlaskPlay" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-494-923
127.0.0.1 - - [03/Apr/2019 14:22:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:22:16] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [03/Apr/2019 14:22:28] "GET /customer-basket HTTP/1.1" 404 -
 * Detected change in '/root/PycharmProjects/Flasksite/FlaskPlay.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-494-923
 * Detected change in '/root/PycharmProjects/Flasksite/FlaskPlay.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-494-923
127.0.0.1 - - [03/Apr/2019 14:23:22] "GET /customer-basket HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:23:27] "GET /customer-basket HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:23:34] "GET /basketball HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:23:37] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [03/Apr/2019 14:25:10] "POST /points HTTP/1.1" 200 -
 * Detected change in '/root/PycharmProjects/Flasksite/FlaskPlay.py', reloading
(1, 4)
[12.23112731]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/tkinter/__init__.py", line 775, in after_cancel
    data = self.tk.call('after', 'info', id)
RuntimeError: main thread is not in main loop
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-494-923
127.0.0.1 - - [03/Apr/2019 14:30:16] "GET /basketball HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:30:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:30:38] "GET /basketball HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:30:41] "GET /customer-basket HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:31:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:31:48] "GET /basketball HTTP/1.1" 200 -
127.0.0.1 - - [03/Apr/2019 14:31:51] "GET /customer-basket HTTP/1.1" 200 -
